# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-13 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='interface_cases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(max_length=20)),
                ('test_id', models.CharField(max_length=20)),
                ('mathod', models.CharField(max_length=10)),
                ('interface_id', models.IntegerField()),
                ('module_id', models.IntegerField()),
                ('project_id', models.IntegerField()),
                ('head', models.TextField()),
                ('data', models.TextField()),
                ('token', models.CharField(max_length=255)),
                ('status', models.IntegerField()),
                ('testcases_createtime', models.DateTimeField(auto_now_add=True)),
                ('testcases_updatetime', models.DateTimeField(auto_now=True)),
                ('testcases_creator', models.CharField(max_length=20)),
                ('testcases_updator', models.CharField(max_length=20)),
                ('comments', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='interfaces',
            fields=[
                ('interface_id', models.AutoField(primary_key=True, serialize=False)),
                ('interface_host', models.CharField(max_length=20, null=True)),
                ('interface_url', models.CharField(max_length=20, null=True)),
                ('module_id', models.IntegerField()),
                ('project_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='monitor_results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255)),
                ('case_id', models.CharField(max_length=255)),
                ('return_code', models.IntegerField()),
                ('expected_contents', models.TextField()),
                ('obtained_contents', models.TextField()),
                ('status', models.IntegerField()),
                ('runtime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='monitor_tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255)),
                ('case_id', models.CharField(max_length=255)),
                ('status', models.IntegerField()),
                ('begintime', models.DateTimeField()),
                ('cycle', models.IntegerField()),
                ('warning_event', models.BooleanField()),
                ('tasks_creator', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='project_module',
            fields=[
                ('module_id', models.AutoField(primary_key=True, serialize=False)),
                ('module_name', models.CharField(max_length=20)),
                ('project_id', models.IntegerField()),
                ('module_createtime', models.DateTimeField(auto_now_add=True)),
                ('module_updatetime', models.DateTimeField(auto_now=True)),
                ('module_creator', models.CharField(max_length=20)),
                ('module_updator', models.CharField(max_length=20)),
                ('modulecomments', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('projects_id', models.AutoField(primary_key=True, serialize=False)),
                ('projects_name', models.CharField(max_length=20)),
                ('projects_status', models.IntegerField()),
                ('projects_createtime', models.DateTimeField(auto_now_add=True)),
                ('projects_updatetime', models.DateTimeField(auto_now=True)),
                ('projects_creator', models.CharField(max_length=20)),
                ('projects_updator', models.CharField(max_length=20)),
                ('projects_comments', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='test_results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_id', models.CharField(max_length=255)),
                ('job_id', models.CharField(max_length=255)),
                ('interfacecase_id', models.CharField(max_length=255)),
                ('return_code', models.IntegerField()),
                ('expected_contents', models.TextField()),
                ('obtained_contents', models.TextField()),
                ('module_id', models.IntegerField()),
                ('project_id', models.IntegerField()),
                ('status', models.IntegerField()),
                ('runtime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='test_tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255)),
                ('case_id', models.CharField(max_length=255)),
                ('status', models.IntegerField()),
                ('begintime', models.DateTimeField()),
                ('endtime', models.DateTimeField()),
                ('tasks_creator', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='testcase_module',
            fields=[
                ('module_id', models.AutoField(primary_key=True, serialize=False)),
                ('module_name', models.CharField(max_length=20)),
                ('project_id', models.IntegerField()),
                ('module_createtime', models.DateTimeField(auto_now_add=True)),
                ('module_updatetime', models.DateTimeField(auto_now=True)),
                ('module_creator', models.CharField(max_length=20)),
                ('module_updator', models.CharField(max_length=20)),
                ('comments', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='testcases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.CharField(max_length=20)),
                ('topic', models.TextField()),
                ('steps', models.TextField()),
                ('expected', models.TextField()),
                ('obtained', models.TextField()),
                ('module_id', models.IntegerField()),
                ('type', models.CharField(max_length=1)),
                ('status', models.IntegerField()),
                ('testcases_createtime', models.DateTimeField(auto_now_add=True)),
                ('testcases_updatetime', models.DateTimeField(auto_now=True)),
                ('testcases_creator', models.CharField(max_length=20)),
                ('testcases_updator', models.CharField(max_length=20)),
                ('comments', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
    ]
