# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-14 01:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0004_auto_20171213_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='projects_comments',
            new_name='project_comments',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='projects_createtime',
            new_name='project_createtime',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='projects_creator',
            new_name='project_creator',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='projects_id',
            new_name='project_id',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='projects_name',
            new_name='project_name',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='projects_status',
            new_name='project_status',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='projects_updatetime',
            new_name='project_updatetime',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='projects_updator',
            new_name='project_updator',
        ),
    ]
